// <auto-generated />
using BuyMe.DL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuyMe.DL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220416051628_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BuyMe.DL.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DiscountPercentage")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("InventoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MRPAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxOrderAmount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountPercentage = 10,
                            Image = "oppo1.png",
                            InStock = true,
                            InventoryId = "Mob-oppo-1",
                            MRPAmount = 15999m,
                            MaxOrderAmount = 3,
                            Name = "Oppo Reno 6"
                        },
                        new
                        {
                            Id = 2,
                            DiscountPercentage = 10,
                            Image = "vivo1.png",
                            InStock = true,
                            InventoryId = "Mob-vivo-1",
                            MRPAmount = 15999m,
                            MaxOrderAmount = 3,
                            Name = "Vivo X"
                        },
                        new
                        {
                            Id = 3,
                            DiscountPercentage = 10,
                            Image = "samsung1.png",
                            InStock = true,
                            InventoryId = "Mob-Sam-1",
                            MRPAmount = 15999m,
                            MaxOrderAmount = 3,
                            Name = "Samsung M31"
                        },
                        new
                        {
                            Id = 4,
                            DiscountPercentage = 10,
                            Image = "IPhone1.png",
                            InStock = true,
                            InventoryId = "Mob-iphone-1",
                            MRPAmount = 15999m,
                            MaxOrderAmount = 3,
                            Name = "Iphone 13 Max pro"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
